
obj-$(CONFIG_PRINTK) += printk.o print_buffer.o

obj-$(CONFIG_REBOOT) += reboot.o

obj-$(CONFIG_RING_BUFFER) += ring_buffer.o

obj-y += generated/

obj-$(CONFIG_SECTION_OVERLAY) += section_overlay.o
