/*
 * Copyright (c) 2017 Actions Semiconductor Co., Ltd
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief link memory address overlay helper
 */

#include <kernel.h>
#include <string.h>
#include <misc/printk.h>
#include <section_overlay.h>

#define SYS_LOG_DOMAIN "overlay"
#define SYS_LOG_LEVEL SYS_LOG_LEVEL_DEBUG
#include <logging/sys_log.h>
#define ACT_LOG_MODEL_ID ALF_MODEL_SECTION_OVERLAY

struct overlay_info {
	u32_t	idcode;

	u32_t	code_vma;
	u32_t	code_size;
	u32_t	code_lma;

	u32_t	data_vma;
	u32_t	data_size;
	u32_t	data_lma;

	u32_t	bss_vma;
	u32_t	bss_size;
};

struct overlay_table
{
	u32_t magic;
	u32_t count;

	const struct overlay_info items[0];
};

/* overlay table is dynamic generated by linker */
extern const struct overlay_table __overlay_table;

static int check_overlay_table(const struct overlay_table *tbl)
{
	if (!tbl || tbl->magic != OVERLAY_TABLE_MAGIC || !tbl->count)
		return -1;

	return 0;
}

void overlay_dump(void)
{
	const struct overlay_info *ovl;
	int i, cnt;

	if (check_overlay_table(&__overlay_table)) {
		ACT_LOG_ID_INF(ALF_STR_overlay_dump__INVALID_OVERLAY_TABL, 0);
		return;
	}

	cnt = __overlay_table.count;

	ACT_LOG_ID_INF(ALF_STR_overlay_dump__SECTION_OVERLAY_TOTA, 1, cnt);

	for (i = 0; i < cnt; i++) {
		ovl = &__overlay_table.items[i];

		ACT_LOG_ID_INF(ALF_STR_overlay_dump____ITEM_D_N, 1, i);
		ACT_LOG_ID_INF(ALF_STR_overlay_dump________IDCODE_DN, 1, ovl->idcode);
		ACT_LOG_ID_INF(ALF_STR_overlay_dump______CODE_VMA_0X08XN, 1, ovl->code_vma);
		ACT_LOG_ID_INF(ALF_STR_overlay_dump_____CODE_SIZE_0X08XN, 1, ovl->code_size);
		ACT_LOG_ID_INF(ALF_STR_overlay_dump______CODE_LMA_0X08XN, 1, ovl->code_lma);
		ACT_LOG_ID_INF(ALF_STR_overlay_dump______DATA_VMA_0X08XN, 1, ovl->data_vma);
		ACT_LOG_ID_INF(ALF_STR_overlay_dump_____DATA_SIZE_0X08XN, 1, ovl->data_size);
		ACT_LOG_ID_INF(ALF_STR_overlay_dump______DATA_LMA_0X08XN, 1, ovl->data_lma);
		ACT_LOG_ID_INF(ALF_STR_overlay_dump_______BSS_VMA_0X08XN, 1, ovl->bss_vma);
		ACT_LOG_ID_INF(ALF_STR_overlay_dump______BSS_SIZE_0X08XN, 1, ovl->bss_size);
	}

}

int overlay_section_init(u32_t idcode)
{
	const struct overlay_info *ovl = NULL;
	int i, cnt;

	ACT_LOG_ID_DBG(ALF_STR_overlay_section_init__INIT_OVERLAY_0XX, 1, idcode);

	if (check_overlay_table(&__overlay_table)) {
		ACT_LOG_ID_WRN(ALF_STR_overlay_section_init__INVALID_OVERLAY_TABL, 0);
		return -1;
	}

	cnt = __overlay_table.count;
	for (i = 0; i < cnt; i++) {
		ovl = &__overlay_table.items[i];
		if (idcode == ovl->idcode)
			break;
	}

	if (cnt == i) {
		ACT_LOG_ID_WRN(ALF_STR_overlay_section_init__CANNOT_FOUND_OVERLAY, 1, idcode);
		return -1;
	}

	if (ovl->code_size) {
		SYS_LOG_DBG("overlay id:0x%x: copy code from 0x%x to 0x%x, size 0x%x\n",
			idcode, ovl->code_lma, ovl->code_vma, ovl->code_size);
		memcpy((char *)ovl->code_vma, (char *)ovl->code_lma, ovl->code_size);
	}

	if (ovl->data_size) {
		SYS_LOG_DBG("overlay id:0x%x: copy data from 0x%x to 0x%x, size 0x%x\n",
			idcode, ovl->data_lma, ovl->data_vma, ovl->data_size);
		memcpy((char *)ovl->data_vma, (char *)ovl->data_lma, ovl->data_size);
	}

	if (ovl->bss_size) {
		SYS_LOG_DBG("overlay id:0x%x: init bss from 0x%x, size 0x%x\n",
			idcode,  ovl->bss_vma, ovl->bss_size);
		memset((char *)ovl->bss_vma, 0x0, ovl->bss_size);
	}

	return 0;
}
