obj-y += btif_base.o
obj-y += btif_a2dp.o
obj-y += btif_avrcp.o
obj-y += btif_hfp.o
obj-y += btif_hfp_ag.o
obj-y += btif_tws.o
obj-y += btif_spp.o
obj-y += btif_pbap.o
obj-y += btif_map.o
obj-y += btif_hid.o
obj-$(CONFIG_BT_PTS_TEST) += btif_pts_test.o
obj-y += btif_audio.o
obj-y += btif_did.o
obj-$(CONFIG_GFP_PROFILE) += btif_gfp.o

ccflags-y += -I${ZEPHYR_BASE}/ext/actions/bluetooth/bt_service/include