ZEPHYRINCLUDE += -I$(srctree)/ext/actions/bluetooth/bt_stack/include/
ZEPHYRINCLUDE += -I$(srctree)/ext/actions/bluetooth/bt_stack/

obj-$(CONFIG_BT_H4) += h4.o
obj-$(CONFIG_BT_H5) += h5.o
obj-$(CONFIG_BT_SPI) += spi.o
obj-$(CONFIG_BT_ACTIONS) += acts_hci.o
