/*
 * Copyright (c) 2019 Actions Semi Co., Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief bt act event id.
*/

#ifndef __BT_ACT_EVENT_ID_H__
#define __BT_ACT_EVENT_ID_H__

enum {
	/***********BR****************/
	EVENT_BT_LINK_ACL_CONNECT_REQ,
	EVENT_BT_LINK_ACL_CONNECTED,
	EVENT_BT_LINK_ACL_DISCONNECTED,
	EVENT_BT_LINK_ROLE_CHANGE,
	EVENT_BT_LINK_SECURITY_CHANGED,
	EVENT_BT_LINK_HF_CONNECTED,
	EVENT_BT_LINK_HF_DISCONNECTED,
	EVENT_BT_LINK_A2DP_CONNECTED,
	EVENT_BT_LINK_A2DP_DISCONNECTED,
	EVENT_BT_LINK_AVRCP_CONNECTED,
	EVENT_BT_LINK_AVRCP_DISCONNECTED,
	EVENT_BT_LINK_SPP_CONNECTED,
	EVENT_BT_LINK_SPP_DISCONNECTED,
	EVENT_BT_LINK_HID_CONNECTED,
	EVENT_BT_LINK_HID_DISCONNECTED,

	EVENT_BT_LINK_ROLE_SET,
	EVENT_BT_A2DP_PKT_MISS,
	EVENT_BT_A2DP_CONFIG_CODEC,
	EVENT_BT_A2DP_STARTED,
	EVENT_BT_A2DP_BREAK_ANOTHER,
	EVENT_BT_A2DP_SUSPEND,

	EVENT_BT_TAKE_OVER,
	/***********LE****************/
	EVENT_LE_CONNECTED,
	EVENT_LE_CONNECTED_ERR,
	EVENT_LE_DISCONNECTED,
	EVENT_LE_DISCONNECTED_ERR,
	EVENT_LE_PARAM_REQ,
	EVENT_LE_PARAM_UPDATED,

	/***********stream****************/
	EVENT_STREAM_LE_CONNECT_CB,
	EVENT_STREAM_LE_RX_NOTIFYIND,
	EVENT_STREAM_SPP_CONNECT_CB,
	EVENT_STREAM_SPP_DISCONNECT_CB,
	/***********broadcast****************/
	EVENT_BTMGR_BROAD_SINK_RELEASE = 100,
	EVENT_BTMGR_BROAD_SINK_DISABLE,
	EVENT_BTMGR_BROAD_SINK_ENABLE,
	EVENT_BTMGR_BROAD_CONFIG,
	EVENT_BTMGR_BROAD_SOURCE_ENABLE,
	EVENT_BTMGR_BROAD_SOURCE_DISABLE,

	EVENT_BTSRV_BMS_CREATE,
	EVENT_BTSRV_BMS_SET_SYNC_CB_OFFSET,
	EVENT_BTSRV_BMS_SET_MEDIA_DELAY,
	EVENT_BTSRV_BMS_START_ADV,
	EVENT_BTSRV_BMS_ENABLE,
	EVENT_BTSRV_BMS_BIS_CONN,
	EVENT_BTSRV_BMS_TX_CONFIGURE,
	EVENT_BTSRV_BMS_TX_PERIOD_CONFIGURE,
	EVENT_BTSRV_BMS_TX_SYNC_CONFIGURE,
	EVENT_BTSRV_BMS_TX_START,
	EVENT_BTSRV_BMS_TX_SYNC_START,
	EVENT_BTSRV_BROAD_SOURCE_STREAM_SET,
	EVENT_BTSRV_BMS_STOP_ADV,
	EVENT_BTSRV_BMS_DISABLE,
	EVENT_BTSRV_BMS_RELEASE,
	EVENT_BTSRV_BMS_BIS_DISCONN,
	EVENT_BTSRV_BMS_TX_UNCONFIGURE,
	EVENT_BTSRV_BMS_TX_PERIOD_UNCONFIGURE,
	EVENT_BTSRV_BMS_TX_SYNC_UNCONFIGURE,

	EVENT_BTSRV_BMR_FILTER_POLICY,
	EVENT_BTSRV_BMR_SYNC_PA,

	EVENT_BTSRV_BMR_PA_SYNCED,
	EVENT_BTSRV_BMR_PA_RECV,
	EVENT_BTSRV_BMR_PA_BIGINFO,
	EVENT_BTSRV_BMR_SYNC_BIG,

	EVENT_BTSRV_BMR_BIS_CONN,

	EVENT_BTSRV_BMR_RX_CONFIGURE,
	EVENT_BTSRV_BMR_RX_PERIOD_CONFIGURE,

	EVENT_BTSRV_BROAD_SINK_STREAM_SET,

	EVENT_BTSRV_BMR_RX_START,
	EVENT_BTSRV_BMR_SCAN_START,
	EVENT_BTSRV_BMR_SCAN_STOP,

	EVENT_BTSRV_BMR_BIS_DISCONN,
	EVENT_BTSRV_BMR_RX_UNCONFIGURE,
	EVENT_BTSRV_BMR_RX_PERIOD_UNCONFIGURE,
	EVENT_BTSRV_BMR_SINK_RESTORE,
};

#define UINT8_ARRAY_TO_INT32(arr) \
    ({                      \
        uint32_t result = 0;\
        for (size_t i = 0; i < sizeof(arr) / sizeof(arr[0]); ++i) {\
            result <<= 8;   \
            result |= (arr[i] & 0xFF);\
        }\
        result;\
    })

#endif