ZEPHYRINCLUDE += -I$(srctree)/ext/actions/bluetooth/bt_service/include
ZEPHYRINCLUDE += -I$(srctree)/ext/actions/bluetooth/bt_stack/src/inc
ZEPHYRINCLUDE += -I$(srctree)/ext/actions/bluetooth/bt_service
ZEPHYRINCLUDE += -I$(srctree)/ext/actions/bluetooth/include/gfp

obj-y += libbt_gfp_api.o
obj-y += helper.o
obj-y += ctr_mode.o