obj-$(CONFIG_DEBUG_COREDUMP) += coredump_core.o coredump_memory_regions.o
obj-$(CONFIG_DEBUG_COREDUMP_BACKEND_LOGGING) += coredump_backend_logging.o
obj-$(CONFIG_DEBUG_COREDUMP_BACKEND_FLASH_DEV) += coredump_backend_flash_dev.o
obj-$(CONFIG_DEBUG_COREDUMP_BACKEND_FLASH_PARTITION) += coredump_backend_flash_partition.o