#
# Copyright (c) 2020 Actions Semiconductor
#
# SPDX-License-Identifier: LicenseRef-BSD-5-Clause-Actions
#
subdir-ccflags-$(CONFIG_BUILD_PROJECT_HM_DEMAND_CODE) += -I$(ZEPHYR_BASE)/samples/bt_speaker/src/charge_6/include
obj-y += bt_manager.o
obj-y += bt_manager_config.o
obj-y += bt_manager_check_mac_name.o
obj-y += bt_manager_connect.o
obj-y += bt_manager_event.o
obj-y += bt_manager_sco.o
obj-y += bt_stream_manager.o
obj-y += bt_manager_audio.o
obj-y += bt_manager_le_audio.o
obj-y += bt_manager_lea_policy.o

obj-$(CONFIG_BT_A2DP) += bt_manager_a2dp.o
obj-$(CONFIG_BT_AVRCP) += bt_manager_avrcp.o
obj-$(CONFIG_BT_HFP_HF) += bt_manager_hfp.o
obj-$(CONFIG_BT_HFP_AG) += bt_manager_hfp_ag.o
obj-$(CONFIG_BT_SPP) += bt_manager_spp.o
obj-$(CONFIG_BT_PBAP_CLIENT) += bt_manager_pbap.o
obj-$(CONFIG_BT_MAP_CLIENT) += bt_manager_map.o
obj-$(CONFIG_BT_HID) += bt_manager_hid.o
obj-$(CONFIG_BT_BLE) += bt_manager_ble.o
obj-$(CONFIG_BT_SPP) += bt_manager_sppble_stream.o
obj-$(CONFIG_BT_BLE) += bt_manager_sppble_stream.o
obj-$(CONFIG_BT_PTS_TEST) += bt_manager_pts_test.o
obj-$(CONFIG_BT_PTS_TEST) += bt_manager_le_pts_test.o
obj-$(CONFIG_MGR_TEST_SAMPLE) += bt_manager_test_sample.o

obj-y += bt_manager_base.o
obj-y += bt_manager_pair.o
obj-y += bt_manager_event.o
obj-y += bt_manager_dev_info.o


obj-y += btmgr_tws_snoop.o
obj-y += btmgr_tws_snoop_poweroff.o
obj-y += btmgr_tws_snoop_ui_event.o

obj-y += audio_service/

obj-y += bt_manager_gatt_over_br.o
obj-y += bt_manager_pawr.o
obj-$(CONFIG_BT_LEATWS) += bt_manager_leatws.o
obj-$(CONFIG_BT_LETWS) += bt_manager_letws.o

obj-y += bt_manager_lea_stereo.o
