obj-$(CONFIG_DMA_QMSI)		+= dma_qmsi.o
obj-$(CONFIG_DMA_STM32F4X)	+= dma_stm32f4x.o
obj-$(CONFIG_DMA_ACTS_ROCKY)	+= dma_acts.o
obj-$(CONFIG_DMA_ACTS_ANDES)	+= dma_acts_andes.o
obj-$(CONFIG_VDMA_ACTS_ANDES)	+= vdma_acts_andes.o rom_vdma_andes.o
