subdir-ccflags-y += -I${ZEPHYR_BASE}/samples/bt_speaker/src/charge_6/include/
subdir-ccflags-y += -I${ZEPHYR_BASE}/samples/bt_speaker/src/charge_6/include/driver/
subdir-ccflags-y += -I${ZEPHYR_BASE}/ext/actions/bluetooth/bt_manager

obj-y += driver/
obj-$(CONFIG_C_EXTERNAL_DSP) += external_dsp/
#obj-$(CONFIG_C_LOGIC_MCU) += logic_mcu/
obj-$(CONFIG_C_SHELL) += shell/
obj-y += self_media_effect/
obj-y += soft_version/
obj-y += run_mode/
obj-y += app/
obj-y += common/
obj-y += ats_cmd/
obj-y += ats_cmd_wlt/
obj-y += gfp_convert_search_api/
obj-y += pd/
obj-y += user_app_init.o
