

obj-y += btsrv_a2dp.o
obj-y += btsrv_a2dp_media.o
obj-y += btsrv_avrcp.o
obj-y += btsrv_hfp.o
obj-y += btsrv_hfp_ag.o
obj-y += btsrv_sco.o
obj-y += btsrv_sco_upload_stream.o
obj-y += btsrv_spp.o
obj-y += btsrv_pbap.o
obj-y += btsrv_hid.o
obj-y += btsrv_map.o
obj-y += btsrv_did.o
ccflags-y += -I${ZEPHYR_BASE}/ext/actions/bluetooth/bt_service/include
ccflags-y += -I${ZEPHYR_BASE}/ext/actions/bluetooth/bt_stack/include
