#) += SPDX-License-Identifier:) += Apache-2.0


obj-$(CONFIG_BT_DIS) += dis.o

obj-$(CONFIG_BT_BAS) += bas.o

obj-$(CONFIG_BT_HRS) += hrs.o

obj-$(CONFIG_BT_TPS) += tps.o

obj-$(CONFIG_BT_HIDS) += hog.o

obj-$(CONFIG_BT_CTS) += cts.o

obj-$(CONFIG_BT_OTS) += ots/
