obj-$(CONFIG_WIFI_RTL8189FTV) += wifi_api.o
obj-$(CONFIG_WIFI_RTL8189FTV) += wifi_conf.o
obj-$(CONFIG_WIFI_RTL8189FTV) += wifi_util.o
obj-$(CONFIG_WIFI_RTL8189FTV) += wifi_ind.o
obj-$(CONFIG_WIFI_RTL8189FTV) += wifi_promisc.o
obj-$(CONFIG_WIFI_RTL8189FTV) += wifi_interactive_mode.o
obj-$(CONFIG_WIFI_RTL8189FTV) += airkiss_api.o