#
# Copyright (c) 2020 Actions Semiconductor
#
# SPDX-License-Identifier: LicenseRef-BSD-5-Clause-Actions
#

obj-y += common_internal.o hci_data_log.o host_interface.o acts_stack_os_depend.o
obj-$(CONFIG_ACTS_NET_BUF) += buf.o
obj-$(CONFIG_BT_SNOOP) += btsnoop.o
obj-$(CONFIG_ACTS_BT_SHELL) += shell/
obj-$(CONFIG_BT_STACK_BQB_TEST) += bqb/
obj-y += bt_stack/
