subdir-ccflags-y += -I${ZEPHYR_BASE}/samples/bt_speaker/src/charge_6/include

obj-y += system_app_init.o
obj-y += system_app_init_input.o
obj-y += system_le_audio.o
obj-y += system_app_shell.o
obj-y += system_audio_policy.o
obj-y += system_tts_policy.o
obj-y += system_event_map.o
obj-y += system_btmgr_config.o
obj-y += system_app.o
obj-y += system_app_bt_callback.o
obj-$(CONFIG_ACTIONS_ATT) += system_app_att.o
obj-$(CONFIG_BT_ADV_MANAGER) += system_ble_advertise.o
obj-$(CONFIG_LOGSRV_SELF_APP) += system_app_log_send.o
obj-y += system_event_tws.o