# SPDX-License-Identifier: Apache-2.0

obj-$(CONFIG_USB_AUDIO_SOURCE_DEV) += usb_audio_source.o
obj-$(CONFIG_USB_AUDIO_SINK) += usb_audio_sink.o
obj-$(CONFIG_USB_AUDIO_SOURCESINK) += audio_sourcesink.o