obj-y += btsrv_rdm.o
obj-y += btsrv_connect.o
obj-y += btsrv_scan.o
obj-y += btsrv_storage.o
obj-y += btsrv_adapter.o
obj-y += btsrv_message.o
obj-y += btsrv_utils.o
obj-y += btsrv_link_adjust.o
obj-y += btsrv_pts_test.o

ccflags-y += -I${ZEPHYR_BASE}/ext/actions/bluetooth/bt_service/include
ccflags-y += -I${ZEPHYR_BASE}/ext/actions/bluetooth/bt_stack/include

obj-y += btsrv_tws_snoop.o
obj-y += btsrv_sniff.o