#
# Copyright (c) 2024 Actions Semiconductor
#
# SPDX-License-Identifier: LicenseRef-BSD-5-Clause-Actions
#

obj-y += bqb_commands.o
obj-y += bqb_core.o
obj-y += bqb_utils.o
obj-y += bqb_gap.o
obj-y += bqb_gatt.o
obj-y += bqb_l2cap.o
obj-y += bqb_sdp.o
obj-y += bqb_rfcomm.o
obj-y += bqb_spp.o
obj-y += bqb_gap_le.o
obj-y += bqb_smp.o
obj-y += bqb_did.o
obj-y += bqb_pbapc.o
obj-y += bqb_gatt.o
obj-y += bqb_hfp_ag.o
obj-y += bqb_hfp_hf.o
obj-y += bqb_a2dp.o
