#
# Copyright (c) 2020 Actions Semiconductor
#
# SPDX-License-Identifier: LicenseRef-BSD-5-Clause-Actions
#

# obj-y += bt_test_data.o bt_test_sample.o bt.o
# obj-$(CONFIG_BT_CONN) += gatt.o
obj-y += bt_1_9.o
obj-$(CONFIG_BT_CONN) += gatt_1_9.o
obj-$(CONFIG_BT_ISO) += iso.o
