subdir-ccflags-y += -I${ZEPHYR_BASE}/samples/bt_speaker/src/charge_6/include

obj-y += main_app.o
obj-y += main_input.o
obj-y += main_view.o
obj-y += main_event.o
obj-$(CONFIG_TWS) += main_event_tws.o