#ifndef __BT_AUDIO_SERVICE_H
#define __BT_AUDIO_SERVICE_H

#include <acts_bluetooth/gatt.h>

#ifdef CONFIG_BT_LE_AUDIO_ENCRYPT
#define BT_AUDIO_GATT_PERM_READ	BT_GATT_PERM_READ_ENCRYPT
#define BT_AUDIO_GATT_PERM_WRITE	BT_GATT_PERM_WRITE_ENCRYPT
#else
#define BT_AUDIO_GATT_PERM_READ	BT_GATT_PERM_READ
#define BT_AUDIO_GATT_PERM_WRITE	BT_GATT_PERM_WRITE
#endif

#endif /* __BT_AUDIO_SERVICE_H */
