# Makefile - CSKY Core Peripheral Access Layer
#
# Copyright (C) 2017 C-SKY Microsystems Co., Ltd. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

ZEPHYRINCLUDE += -I$(srctree)/ext/hal/csky/csi/csi_core/include/
