# SPDX-License-Identifier: Apache-2.0

obj-$(CONFIG_USB_MASS_STORAGE) += mass_storage.o
obj-$(CONFIG_USB_CDC_ACM) += cdc_acm.o
obj-$(CONFIG_USB_AUDIO_CLASS) += audio/
obj-$(CONFIG_USB_DEVICE_HID) += hid/
obj-$(CONFIG_USB_DEVICE_STUB) += stub/
obj-$(CONFIG_USB_DEVICE_DFU) += dfu/